### ISSUE TITLE
Usage for frontend live chat

### ISSUE THREAD

**Issue by rafaelpatro** [steverobbins/Magento-Slack#1]
Hi man, you have a great job here. Congrats!

One doubt. Can I use your API to make a frontend live chat for Magento 1.9? How would it work? Is there another git projects that I could see an example?
Thanks and have a nice week.

**Comment by steverobbins** [comment]
The project doesn't implement anything specific.  You would have to build a live chat of your own.  Though, I don't see a way to get message from the API: https://api.slack.com/methods
